services:
  backend:
    container_name: "backend"
    build:
      context: .  # Backend Dockerfile'ının bulunduğu dizin
      dockerfile: ./Dockerfile  # Dockerfile yolu
    ports:
      - "5142:8080"  # Backend portu
    depends_on:
      - sqlserver  # SQL Server'a bağlı
      - rabbitmq   # RabbitMQ'ya bağlı
      - redis       # Redis'e bağlı
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Data Source=localhost,1433;Initial Catalog=northwind;User ID=sa;Password=Yy654321**;TrustServerCertificate=True
    networks:
      - mynetwork

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "Yy654321**"  # Güçlü bir parola
      ACCEPT_EULA: "Y"  # EULA kabulü
    ports:
      - "1433:1433"  # SQL Server portu
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:management
    container_name: "rabbitmq"
    ports:
      - "5672:5672"  # RabbitMQ messaging portu
      - "15672:15672"  # RabbitMQ yönetim paneli portu
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # Redis default portu
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
