services:
  backend:
    container_name: "backend"
    build:
      context: .  # Backend Dockerfile'ının bulunduğu dizin
      dockerfile: ./Dockerfile  # Dockerfile yolu
    ports:
      - "5142:8080"  # Backend portu
    depends_on:
      - rabbitmq   # RabbitMQ'ya bağlı
      - redis       # Redis'e bağlı
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Server=134.122.68.208,1433;Database=northwind;User Id=sa;Password=Yy654321**;TrustServerCertificate=True;
    networks:
      - mynetwork
  rabbitmq:
    image: rabbitmq:management
    container_name: "rabbitmq"
    ports:
      - "5672:5672"  # RabbitMQ messaging portu
      - "15672:15672"  # RabbitMQ yönetim paneli portu
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - mynetwork

  redis:
    image: redis:latest
    ports:
      - "6379:6379"  # Redis default portu
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
